# Standalone ADT/LLM/regex diagnostics used by 05_figures.Rmd. All writes use
# the main pipeline's save_fig, so progress, atomic saves and overwrite apply.
metastatic_label_pairs <- function() {
  pairs <- list(adt_vs_llm = c("ADT_LABEL", "LLM_LABEL"))
  for (stage in c("REGEX_LABEL", "REGEX_MAX_BEFORE", "REGEX_MAX_AFTER")) {
    for (label in c("ADT_LABEL", "LLM_LABEL"))
      pairs[[tolower(paste(label, "vs", stage, sep = "_"))]] <- c(label, stage)
  }
  pairs
}

metastatic_pair_counts <- function(labels, first, second) {
  levels <- c("Local", "Metastatic")
  paired <- labels %>% filter(.data[[first]] %in% levels, .data[[second]] %in% levels)
  counts <- paired %>% transmute(first = .data[[first]], second = .data[[second]]) %>%
    count(first, second, name = "n") %>%
    complete(first = levels, second = levels, fill = list(n = 0L)) %>%
    group_by(first) %>% mutate(row_n = sum(n), fraction = if_else(row_n > 0, n / row_n, NA_real_)) %>%
    ungroup()
  list(counts = counts, paired = nrow(paired), missing = nrow(labels) - nrow(paired),
       agreement = if (nrow(paired)) mean(paired[[first]] == paired[[second]]) else NA_real_)
}

metastatic_supplement_stems <- function() {
  paste0("adt_labels_", c("coverage", names(metastatic_label_pairs()),
    outer(c("adt", "llm"), c("burden", "sites", "km_death", "km_platinum", "km_nepc",
                              "trajectory_psa", "trajectory_testosterone"), paste, sep = "_")))
}

render_metastatic_supplements <- function(config, patient_df, labs, save_panel,
                                         notify, show = FALSE) {
  notify("stage", "Supplement: ADT, LLM metastatic and collapsed regex stage")
  required <- c(intent = config$intent, stage = config$stage, llm = config$llm)
  missing <- required[!file.exists(required)]
  if (length(missing)) {
    warning("Metastatic-label supplement skipped; missing input(s): ",
            paste(missing, collapse = ", "),
            ". ADT labels are generated by compass_pipeline.build_adt_intent_mrn_lists().")
    return(invisible(NULL))
  }
  tmp <- tempfile("compass-metastatic-labels-", fileext = ".csv")
  on.exit(unlink(tmp), add = TRUE)
  args <- c(config$script, "--intent", config$intent, "--stage", config$stage,
            "--llm", config$llm, "--output", tmp)
  if (!is.null(config$icd)) args <- c(args, "--icd", config$icd)
  status <- system2(config$python, vapply(args, shQuote, character(1)))
  if (status != 0L || !file.exists(tmp)) stop("Metastatic-label preparation failed (Python exit ", status, ")")
  labels <- readr::read_csv(tmp, col_types = readr::cols(DFCI_MRN = readr::col_character()),
                           show_col_types = FALSE)
  labels <- patient_df %>% select(DFCI_MRN) %>% mutate(DFCI_MRN = as.character(DFCI_MRN)) %>%
    left_join(labels, by = "DFCI_MRN")
  if ("TREATMENT_ANCHOR_DATE" %in% names(patient_df)) {
    difference <- abs(as.numeric(as.Date(patient_df$TREATMENT_ANCHOR_DATE) - as.Date(labels$ADT_FIRST_DATE)))
    if (any(difference > 1, na.rm = TRUE))
      stop("Metastatic supplement: longitudinal ADT anchors disagree with intent-label ADT_FIRST_DATE")
  }
  names_pretty <- c(ADT_LABEL = "ADT intent", LLM_LABEL = "LLM metastatic status",
                    REGEX_LABEL = "Regex stage nearest before ADT (365 days)",
                    REGEX_MAX_BEFORE = "Regex maximum stage before ADT",
                    REGEX_MAX_AFTER = "Regex maximum stage after ADT")
  colors <- c(Local = "#0b6ba8", Metastatic = "#c1272d", Unclassified = "#999999")
  caption <- paste("Canonical ADT analysis cohort; pre-ADT castrate patients included.",
                   "Regex I–III = local; IV = metastatic. ADT/LLM labels use full observed history.",
                   "Agreement is descriptive; definitions and observation windows differ.", sep = "\n")
  emit <- function(plot, name, width = 8, height = 5.5) {
    save_panel(plot, paste0("adt_labels_", name), width, height)
    if (show) print(plot)
  }
  coverage <- labels %>% select(all_of(names(names_pretty))) %>%
    pivot_longer(everything(), names_to = "source", values_to = "label") %>%
    mutate(label = coalesce(label, "Unclassified")) %>% count(source, label)
  emit(ggplot(coverage, aes(x = source, y = n, fill = label)) + geom_col() +
         geom_text(aes(label = n), position = position_stack(vjust = .5), size = 3) +
         scale_x_discrete(labels = names_pretty) + scale_fill_manual(values = colors) +
         coord_flip() + labs(x = NULL, y = "Patients", fill = NULL,
                            title = "Label coverage and local/metastatic composition", caption = caption) +
         theme_bw(), "coverage", 9, 6)

  for (name in names(metastatic_label_pairs())) {
    pair <- metastatic_label_pairs()[[name]]
    result <- metastatic_pair_counts(labels, pair[1], pair[2])
    d <- result$counts %>% mutate(text = if_else(row_n > 0,
      sprintf("n = %s\n%.1f%%", n, 100 * fraction), sprintf("n = %s\nNA", n)))
    subtitle <- sprintf("Both labelled: %s of %s; missing either: %s; agreement: %s",
      result$paired, nrow(labels), result$missing,
      if (result$paired) sprintf("%.1f%%", 100 * result$agreement) else "NA")
    emit(ggplot(d, aes(second, first, fill = fraction)) + geom_tile(color = "white") +
           geom_text(aes(label = text), size = 4) +
           scale_fill_gradient(low = "white", high = "#56B4E9", limits = c(0, 1), na.value = "grey90") +
           scale_x_discrete(limits = c("Local", "Metastatic")) +
           scale_y_discrete(limits = c("Metastatic", "Local")) +
           labs(x = names_pretty[[pair[2]]], y = names_pretty[[pair[1]]],
                title = "Local versus metastatic label agreement", subtitle = subtitle,
                fill = "Row fraction", caption = caption) + theme_bw(), name, 9, 6)
  }

  # Merge the old ADT filtering diagnostics, also displaying the LLM definition.
  # Reuse the parent's patient and androgen caches; never parse the large CSV again.
  for (source in c("ADT_LABEL", "LLM_LABEL")) {
    slug <- if (source == "ADT_LABEL") "adt" else "llm"
    grouped <- labels %>% mutate(label = .data[[source]]) %>% filter(!is.na(label))
    if ("N_MET_SITES" %in% names(grouped)) {
      burden <- grouped %>% filter(!is.na(N_MET_SITES)) %>%
        mutate(sites = if_else(N_MET_SITES >= 2, "2+", as.character(N_MET_SITES))) %>% count(label, sites)
      emit(ggplot(burden, aes(sites, n, fill = label)) + geom_col(position = "dodge") +
             scale_fill_manual(values = colors) + labs(x = "Distinct ICD metastatic sites at ADT", y = "Patients",
             fill = names_pretty[[source]], caption = caption) + theme_bw(), paste0(slug, "_burden"))
      sites <- grouped %>% select(label, starts_with("MET_SITE_")) %>%
        pivot_longer(-label, names_to = "site", values_to = "present") %>%
        filter(!is.na(present)) %>% group_by(label, site) %>% summarise(fraction = mean(present), .groups = "drop")
      if (nrow(sites)) emit(ggplot(sites, aes(site, fraction, fill = label)) + geom_col(position = "dodge") +
        coord_flip() + scale_fill_manual(values = colors) + labs(x = NULL, y = "Proportion with coded site",
        fill = names_pretty[[source]], caption = caption) + theme_bw(), paste0(slug, "_sites"))
    }
    patients <- patient_df %>% mutate(DFCI_MRN = as.character(DFCI_MRN)) %>%
      inner_join(grouped %>% select(DFCI_MRN, label), by = "DFCI_MRN")
    for (endpoint in c("death", "platinum", "nepc")) {
      duration_col <- paste0("t_", endpoint)
      event_col <- toupper(endpoint)
      if (!all(c(duration_col, event_col) %in% names(patients))) next
      d <- patients %>% transmute(label, duration = as.numeric(.data[[duration_col]]),
                                  event = as.numeric(.data[[event_col]]))
      # Death uses last contact for censored patients, as the parent KM does.
      if (endpoint == "death" && "t_last_contact" %in% names(patients))
        d$duration <- ifelse(d$event == 0, as.numeric(patients$t_last_contact), d$duration)
      d <- d %>% filter(is.finite(duration), duration > 0, event %in% c(0, 1))
      if (!nrow(d)) next
      fit <- survival::survfit(survival::Surv(duration, event) ~ label, data = d)
      sf <- summary(fit, censored = TRUE)
      strata <- if (is.null(sf$strata)) rep(unique(d$label), length(sf$time)) else
        sub("^label=", "", as.character(sf$strata))
      curve <- tibble(time = sf$time / 365.25, survival = sf$surv, label = strata)
      curve <- bind_rows(tibble(time = 0, survival = 1, label = unique(d$label)), curve)
      counts <- d %>% group_by(label) %>% summarise(n = n(), events = sum(event), .groups = "drop")
      emit(ggplot(curve, aes(time, survival, color = label)) + geom_step() +
        scale_color_manual(values = colors) + coord_cartesian(ylim = c(0, 1)) +
        labs(x = "Years from ADT", y = if (endpoint == "death") "Overall survival" else "Event-free probability",
             title = paste(toupper(endpoint), "by", names_pretty[[source]]),
             subtitle = paste(sprintf("%s: n=%s, events=%s", counts$label, counts$n, counts$events), collapse = "; "),
             color = NULL, caption = caption) + theme_bw(), paste0(slug, "_km_", endpoint))
    }
    for (lab in c("PSA", "Testosterone")) {
      d <- labs %>% filter(LAB_GROUP == lab, is.finite(LAB_VALUE), LAB_VALUE >= 0,
                          t_rel >= -365, t_rel <= 5 * 365) %>%
        mutate(DFCI_MRN = as.character(DFCI_MRN), bin = floor(t_rel / 180) * 180) %>%
        inner_join(grouped %>% select(DFCI_MRN, label), by = "DFCI_MRN") %>%
        group_by(DFCI_MRN, label, bin) %>% summarise(value = mean(LAB_VALUE), .groups = "drop") %>%
        group_by(label, bin) %>% summarise(n = n(), median = median(value),
          q1 = quantile(value, .25), q3 = quantile(value, .75), .groups = "drop") %>% filter(n >= 5)
      if (!nrow(d)) next
      if (lab == "PSA") d <- d %>% mutate(across(c(median, q1, q3), ~ pmax(.x, .01)))
      p <- ggplot(d, aes((bin + 90) / 365.25, median, color = label, fill = label)) +
        geom_ribbon(aes(ymin = q1, ymax = q3), alpha = .15, color = NA) + geom_line() +
        geom_vline(xintercept = 0, linetype = "dashed") +
        scale_color_manual(values = colors) + scale_fill_manual(values = colors) +
        labs(x = "Years from ADT", y = lab, color = NULL, fill = NULL,
             title = paste(lab, "by", names_pretty[[source]]),
             subtitle = "180-day bins; patient means then median/IQR; at least 5 patients per bin",
             caption = caption) + theme_bw()
      if (lab == "PSA") p <- p + scale_y_log10()
      if (lab == "Testosterone") p <- p + geom_hline(yintercept = c(20, 50), linetype = "dotted")
      emit(p, paste0(slug, "_trajectory_", tolower(lab)))
    }
  }
  invisible(labels)
}
